const CREATE_MIGRATIONS_TABLE_QUERY = `
  CREATE TABLE IF NOT EXISTS migrations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`
const GET_ALL_MIGRATIONS_QUERY = `SELECT * FROM migrations ORDER BY applied_at DESC`
const INSERT_MIGRATION_QUERY = `INSERT INTO migrations (name) VALUES (?)`

export default {
  CREATE_MIGRATIONS_TABLE_QUERY,
  GET_ALL_MIGRATIONS_QUERY,
  INSERT_MIGRATION_QUERY
}
